[package]
name = "network"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "udp-server"
path = "src/udp-server.rs"

[[bin]]
name = "udp-client"
path = "src/udp-client.rs"

[[bin]]
name = "tcp-server"
path = "src/tcp-server.rs"

[[bin]]
name = "tcp-client"
path = "src/tcp-client.rs"

[dependencies]
